### ISSUE TITLE
GitHub page is not working

### ISSUE THREAD

**Issue by MrSlimCoder** [chryz-hub/Chryz-Hub-Blogs#16]

**Comment by MrSlimCoder** [comment]
@chryzcodez http://chryz-hub.github.io/Chryz-Hub-Blogs is throwing 404 Error.

**Comment by chryzcode** [comment]
we are yet to host it and we can't host this with GitHub Pages, it is not going to work. Using Heroku is the best. 

And I'm presently styling the Blog Project
